apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
  description: Default group for demo ownership
spec:
  type: team
  children: []
---
kind: System
metadata:
  name: devpath-platform
  description: DevPath Internal Developer Platform
  tags:
    - platform
    - gitops
    - kubernetes
spec:
  owner: guests
